### ISSUE TITLE
Output SVG

### ISSUE THREAD

**Issue by domi41** [MieuxVoter/majority-judgment-cli#11]
mj --format svg --chart merit > merit.svg

I'm not going to take this on, since we already have `gnuplot` and my plate is full with detailed judgments as input and normalization.

Make sure to ping @roipoussiere about this, since he gave the subject a lot of thought already.

**Comment by kepon85** [comment]
Bonjour @domi41 

Effectivement l'implémentation SVG n'est pas faite : 

panic: todo: see issue https://github.com/MieuxVoter/majority-judgment-cli/issues/11

```
goroutine 1 [running]:
github.com/MieuxVoter/majority-judgment-cli/cmd.init.func1(0xb56280, {0xc0000c4460, 0x4?, 0x8093f5?})
	/home/david/bin/majority-judgment-cli/cmd/root.go:127 +0x1685
github.com/spf13/cobra.(*Command).execute(0xb56280, {0xc000016250, 0x5, 0x5})
	/root/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x691
github.com/spf13/cobra.(*Command).ExecuteC(0xb56280)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x38e
github.com/spf13/cobra.(*Command).Execute(...)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/MieuxVoter/majority-judgment-cli/cmd.Execute()
	/home/david/bin/majority-judgment-cli/cmd/root.go:278 +0x1a
main.main()
	/home/david/bin/majority-judgment-cli/main.go:13 +0xf
exit status 2
```

Une façon de faire du SVG avec ce qui est implémenté, c'est avec gnuplot si on modifie juste : _formatter/formatter.go_

```diff
< set term wxt \
<    persist \
> set terminal svg \
    size 1000, ` + strconv.Itoa(plotHeight) + ` \
<    #position 300, 200 \
    background rgb '#f0f0f0' \
<    title 'Merit Profiles' \
    font ',12'
```

Ensuite : 
`go run . example/example.csv --sort  --format gnuplot | gnuplot > sortie.svg`

On obtient un beau SVG

**Comment by domi41** [comment]
See #33
